# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'staging: Deploy Azure Static Web App'

env:
  FORCE_COLOR: true # See: https://github.com/actions/setup-node/issues/317#issuecomment-929694556

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Build And Deploy to Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PEBBLE_0707A6B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'www'
          app_build_command: 'npm run build:production'
        env:
          NG_PRODUCTION: ${{ secrets.STAGE_NG_PRODUCTION }}
          ENV_NAME: ${{ secrets.STAGE_ENV_NAME }}
          NG_USE_SERVICE_WORKER: ${{ secrets.STAGE_NG_USE_SERVICE_WORKER }}
          TXT_APP_NAME: 'Helpful Information'
          TXT_MAIN_PAGE_HEADER: 'The Netherlands Red Cross provides Helpful Information.'
          TXT_MAIN_PAGE_INTRO: 'Please choose a location.'
          REGIONS: ${{ secrets.STAGE_REGIONS }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.STAGE_GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SHEETS_API_URL: ${{ secrets.GOOGLE_SHEETS_API_URL }}
          GOOGLE_SHEETS_SHEET_IDS: ${{ secrets.STAGE_GOOGLE_SHEETS_SHEET_IDS }}
          NG_AI_IKEY: ${{ secrets.NG_AI_IKEY }}
          NG_AI_ENDPOINT: ${{ secrets.NG_AI_ENDPOINT }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request for Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PEBBLE_0707A6B03 }}
          action: 'close'
